name: check lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: npm install
      run: npm install
    - name: npm run lint
      run: npm run lint
