name: check lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: move
      run: cd ..
    - name: npm install
      run: npm install
    - name: npm run lint
      run: npm run lint
